server:
  port: 8086

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/NextBI?serverTimezone=Asia/Tokyo&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: root

  data:
    redis:
      host: localhost
      port: 6379
      #password:
      database: 0

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
